### ISSUE TITLE
Website links return 404

### ISSUE THREAD

**Issue by Ionaru** [yarnpkg/website#367]
On https://yarnpkg.com the 'getting started' menu button links to https://yarnpkg.com/docs/getting-started, this link goes to a 404 page. The correct link should be https://yarnpkg.com/lang/en/docs/getting-started/

Seems the language choice is not preserved while linking through the website, which results in a wrong URL.

Using Opera 42.0.2393.517 on Ubuntu 16.10
Browser ID: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.517

**Comment by DomClayton** [comment]
Also possibly related, when visiting https://yarnpkg.com/ I'm seeing a page with just this link: 

> [Click here to see the site](https://yarnpkg.com/lang/en/)

I'm expecting this is meant to automatically redirect.

**Comment by onemenzel** [comment]
I get this using Opera and Safari in their newest versions. Firefox and Chrome are working though.

**Comment by amitmtrn** [comment]
clicking on getting started link to https://yarnpkg.com/docs/getting-started
and should link to https://yarnpkg.com/lang/en/docs/getting-started/

**Comment by israphim** [comment]
workaround: click on the language selector and manually select english

**Comment by Daniel15** [comment]
Does anyone in this thread have their preferred language set to something other than English? My hunch is  that there's a bug that's occurring for anyone that uses a language that the site doesn't support.

**Comment by Daniel15** [comment]
cc @thejameskyle

**Comment by onemenzel** [comment]
German here. Now that you mention it: my default language is set to English in Firefox. And on my language list in Chrome it's No. 1.

**Comment by Daniel15** [comment]
Thanks for the confirmation. I can repro in Firefox if I change my language preference to German:
![](http://ss.dan.cx/2017/02/firefox_01-15.17.40.png)

**Comment by gotofritz** [comment]
Doesn't work for me on either firefox or chrome canary, but it works on safari.
I am in Germany with an English OS and browsers.

**Comment by thejameskyle** [comment]
I figured out the issue, I'll publish a fix soon

**Comment by thejameskyle** [comment]
Fixed

**Comment by petermikitsh** [comment]
I still can't access the getting started page. I wanted to setup yarn on my CentOS CI server :(
