### ISSUE TITLE
Document --freeze-lockfile

### ISSUE THREAD

**Issue by victornoel** [yarnpkg/website#378]
It would be great to have a documentation of what `--freeze-lockfile` exactly do and how it differs from `--pure-lockfile` :)

Thanks!

(was yarnpkg/yarn#2478).

**Comment by lawliet89** [comment]
`--frozen-lockfile` is inspired by [bundler's](http://bundler.io/v1.14/bundle_install.html) analogue. 

`--pure-lockfile` will install as normal, and at the end of the process, it simply [does not](https://github.com/yarnpkg/yarn/blob/3dc9cf43448da51d3b8890de339a0ed27b12ca62/src/cli/commands/install.js#L583) update the lockfile at all.

`--frozen-lockfile` will [check](https://github.com/yarnpkg/yarn/blob/3dc9cf43448da51d3b8890de339a0ed27b12ca62/src/cli/commands/install.js#L307) early in the install process, after dependencies are resolved but before anything is installed, that the lockfile is up to date and in sync. If this check fails, it will return an error.

**Comment by sdtsui** [comment]
+1 on seeing this added to the website.

**Comment by bestander** [comment]
Send a PR please

**Comment by BYK** [comment]
Hi @lawliet89! You seem to have a good understanding. Up for a PR? I'd love to help too.

**Comment by denisflorkin** [comment]
Hi 
reading @lawliet89 

> --pure-lockfile will install as normal, 

does "normal" means that this effectively prevent "newer" version of current deps (locked in lockfile) to be installed ?
Or is there a possibility that some deps would be updated while the lockfile is not ?

**Comment by tvainika** [comment]
Fixed in #574 ?

**Comment by BYK** [comment]
@tvainika the difference between `--pure-lockfile` and `--frozen-lockfile` is still not explained so not yet resolved I'd say :)

**Comment by dherges** [comment]
```bash
$ yarn --help
    --no-lockfile                       don't read or generate a lockfile
    --pure-lockfile                     don't generate a lockfile
    --frozen-lockfile                   don't generate a lockfile and fail if an update is needed
```

**Comment by victornoel** [comment]
ok, I think we can say that now it's clear :)
